export const UPDATE_LISTITEMS = 'UPDATE_LISTITEMS';
export const REMOVE_LISTITEM = 'REMOVE_LISTITEM';
export const SET_CURRENT_LISTITEM = 'SET_CURRENT_LISTITEM';
export const ADD_LISTITEM = 'ADD_LISTITEM';
export const LOADING = 'LOADING';